import matplotlib.pyplot as plt
import pandas as pd 
import ast
import numpy as np
from matplotlib.ticker import MaxNLocator
from pathlib import Path

# Ensure that the figures directory exists
Path("figures").mkdir(parents=True, exist_ok=True)

# Read general .txt or .csv file and return number values in dictionary
# Generated by Claude (Sept 2026) w/ prompt "can you write a function reading csv and txt files separated by \t, given this writing function (insert writeToFile)"
def readResultsFile(filename):
    df = pd.read_csv(filename, sep="\t") # read file
    data = {}
    for col in df.columns:
        first_val = str(df[col].iloc[0]).strip() # labels
        if first_val.startswith("["): # if array or list
            data[col] = np.array([np.array(ast.literal_eval(v)) for v in df[col]], dtype = object)
        else: # single number values
            data[col] = df[col].to_numpy()
    return data

# =====================================================================
# PART G: Lasso regression with gradient descent
# Written with Claude (Sept 2026)
# =====================================================================
res_g = Path("results") / "part=g"

# Colours: same as method_styles above (parts e, f)
c_plain    = "tab:blue"
c_momentum = "tab:orange"
c_adagrad  = "tab:green"
c_rmsprop  = "tab:red"
c_adam     = "tab:purple"
c_soft     = "k"

# ---------------------------------------------------------------------
# Figure 1: Lasso coefficients, subgradient vs soft thresholding
# ---------------------------------------------------------------------
data_g = readResultsFile(res_g / "n=100_noise=0.1_d=5_type=lambda_sweep_results.txt")
lam_g = data_g["lambda"]
meth_g = data_g["method"]
chosen_lambda = 1e-2

theta_plain = np.abs(np.asarray(data_g["theta"][(meth_g == "plain")          & np.isclose(lam_g, chosen_lambda)][0], dtype=float))
theta_adam  = np.abs(np.asarray(data_g["theta"][(meth_g == "adam")           & np.isclose(lam_g, chosen_lambda)][0], dtype=float))
theta_soft  = np.abs(np.asarray(data_g["theta"][(meth_g == "soft_threshold") & np.isclose(lam_g, chosen_lambda)][0], dtype=float))
j = np.arange(1, len(theta_plain) + 1)

plt.figure(figsize=(3.7, 2.8))
plt.plot(j, theta_plain, marker = "o", color = c_plain, label = "Subgradient, plain GD")
plt.plot(j, theta_adam,  marker = "s", color = c_adam,  label = "Subgradient, Adam")
plt.plot(j, np.where(theta_soft > 0, theta_soft, np.nan), marker = "*", markersize = 9,
         linestyle = "--", color = c_soft, label = "Soft thresholding")   # exact zeros -> gaps
plt.yscale("log")
plt.ylim(1e-6, 2)
plt.xlabel(r"Coefficient index $j$ (power $x^j$)")
plt.ylabel(r"$|\theta_j|$")
plt.grid()
plt.xlim(np.min(j), np.max(j))
plt.legend(loc = "upper left", bbox_to_anchor = (1.02, 1), frameon = False)
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.savefig("figures/n=100_noise=0.1_exercise=g_coefficients_Lasso.pdf", bbox_inches='tight')
#plt.show()

# ---------------------------------------------------------------------
# Figure 2: distance from the scikit-learn minimum vs lambda
# ---------------------------------------------------------------------
floor = 1e-14   # values at machine precision are drawn on this line instead of disappearing

lam_plain = lam_g[meth_g == "plain"];          gap_plain    = data_g["cost_diff_sklearn"][meth_g == "plain"]
lam_mom   = lam_g[meth_g == "momentum"];       gap_momentum = data_g["cost_diff_sklearn"][meth_g == "momentum"]
lam_ada   = lam_g[meth_g == "adagrad"];        gap_adagrad  = data_g["cost_diff_sklearn"][meth_g == "adagrad"]
lam_rms   = lam_g[meth_g == "rmsprop"];        gap_rmsprop  = data_g["cost_diff_sklearn"][meth_g == "rmsprop"]
lam_adam  = lam_g[meth_g == "adam"];           gap_adam     = data_g["cost_diff_sklearn"][meth_g == "adam"]
lam_soft  = lam_g[meth_g == "soft_threshold"]; gap_soft     = data_g["cost_diff_sklearn"][meth_g == "soft_threshold"]

plt.figure(figsize=(3.7, 2.8))
plt.plot(lam_plain, np.maximum(gap_plain,    floor), color = c_plain,    label = "Plain GD")
plt.plot(lam_mom,   np.maximum(gap_momentum, floor), color = c_momentum, label = "Momentum")
plt.plot(lam_ada,   np.maximum(gap_adagrad,  floor), color = c_adagrad,  label = "AdaGrad")
plt.plot(lam_rms,   np.maximum(gap_rmsprop,  floor), color = c_rmsprop,  label = "RMSprop")
plt.plot(lam_adam,  np.maximum(gap_adam,     floor), color = c_adam,     label = "Adam")
plt.plot(lam_soft,  np.maximum(gap_soft,     floor), color = c_soft, linestyle = "--", label = "Soft thresholding")
plt.xscale("log")
plt.yscale("log")
plt.ylim(floor / 2, 1)
plt.xlabel(r"Penalty $(\lambda)$")
plt.ylabel(r"$C(\boldsymbol{\theta}) - C(\boldsymbol{\theta}_{\mathrm{sklearn}})$")
plt.grid()
plt.xlim(np.min(lam_plain), np.max(lam_plain))
plt.legend(loc = "upper left", bbox_to_anchor = (1.02, 1), frameon = False)
plt.savefig("figures/n=100_noise=0.1_exercise=g_cost_vs_lambda_Lasso.pdf", bbox_inches='tight')
#plt.show()

# ---------------------------------------------------------------------
# Figure 3: test MSE vs degree, OLS / Ridge / Lasso, exact vs Adam
# ---------------------------------------------------------------------
data_gd = readResultsFile(res_g / "n=100_noise=0.1_lambda=0.01_type=degree_sweep_results.txt")
model_g = data_gd["model"]
meth_gd = data_gd["method"]
d_g     = data_gd["d"]

d_ols   = d_g[(model_g == "OLS")   & (meth_gd == "exact")]
d_ridge = d_g[(model_g == "Ridge") & (meth_gd == "exact")]
d_lasso = d_g[(model_g == "Lasso") & (meth_gd == "exact")]
mse_ols_exact   = data_gd["MSE"][(model_g == "OLS")   & (meth_gd == "exact")]
mse_ols_adam    = data_gd["MSE"][(model_g == "OLS")   & (meth_gd == "adam")]
mse_ridge_exact = data_gd["MSE"][(model_g == "Ridge") & (meth_gd == "exact")]
mse_ridge_adam  = data_gd["MSE"][(model_g == "Ridge") & (meth_gd == "adam")]
mse_lasso_exact = data_gd["MSE"][(model_g == "Lasso") & (meth_gd == "exact")]
mse_lasso_adam  = data_gd["MSE"][(model_g == "Lasso") & (meth_gd == "adam")]

plt.figure(figsize=(3.7, 2.8))
plt.plot(d_ols,   mse_ols_exact,   color = "b",             label = "OLS (exact)")
plt.plot(d_ols,   mse_ols_adam,    color = "b",             linestyle = "--", marker = "*", markersize = 4, label = "OLS (Adam)")
plt.plot(d_ridge, mse_ridge_exact, color = "palevioletred", label = "Ridge (exact)")
plt.plot(d_ridge, mse_ridge_adam,  color = "palevioletred", linestyle = "--", marker = "*", markersize = 4, label = "Ridge (Adam)")
plt.plot(d_lasso, mse_lasso_exact, color = "k",             label = "Lasso (exact)")
plt.plot(d_lasso, mse_lasso_adam,  color = "k",             linestyle = "--", marker = "*", markersize = 4, label = "Lasso (Adam)")
plt.yscale("log")
plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel("MSE")
plt.grid()
plt.xlim(np.min(d_ols), np.max(d_ols))
plt.legend(loc = "upper left", bbox_to_anchor = (1.02, 1), frameon = False)
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.savefig("figures/n=100_noise=0.1_exercise=g_MSE_vs_degree_OLS_Ridge_Lasso.pdf", bbox_inches='tight')
#plt.show()

# ---------------------------------------------------------------------
# Figure 4: learning-rate sensitivity for Lasso (panel (c) next to part f)
# Same size / style as the part f sensitivity figures so they sit side by side
# ---------------------------------------------------------------------
data_lr = readResultsFile(res_g / "n=100_noise=0.1_d=5_lambda=0.01_type=lr_sensitivity_results.txt")
meth_lr = data_lr["method"]
lr      = data_lr["learning_rate"]
err     = data_lr["final_param_error"]

fig, ax = plt.subplots(figsize=(6.5, 4.5), dpi=300)
ax.plot(lr[meth_lr == "plain"],          err[meth_lr == "plain"],          color = c_plain,    linewidth = 1.8, label = "Plain GD")
ax.plot(lr[meth_lr == "momentum"],       err[meth_lr == "momentum"],       color = c_momentum, linewidth = 1.8, label = "Momentum")
ax.plot(lr[meth_lr == "adagrad"],        err[meth_lr == "adagrad"],        color = c_adagrad,  linewidth = 1.8, label = "AdaGrad")
ax.plot(lr[meth_lr == "rmsprop"],        err[meth_lr == "rmsprop"],        color = c_rmsprop,  linewidth = 1.8, label = "RMSprop")
ax.plot(lr[meth_lr == "adam"],           err[meth_lr == "adam"],           color = c_adam,     linewidth = 1.8, label = "Adam")
ax.plot(lr[meth_lr == "soft_threshold"], err[meth_lr == "soft_threshold"], color = c_soft,     linewidth = 1.8, linestyle = "--", label = "Soft thresholding")
ax.axhline(1e-8, color = "black", linestyle = ":", alpha = 0.7, label = r"Target ($10^{-8}$)")
ax.set_xscale("log")
ax.set_yscale("log")
ax.set_ylim(1e-12, 1e3)
ax.set_xlabel(r"Initial learning rate ($\gamma$)", fontsize = 11)
ax.set_ylabel(r"$\max |\boldsymbol{\theta}_{\mathrm{final}} - \boldsymbol{\theta}_{\mathrm{sklearn}}|$", fontsize = 11)
ax.grid(True, which = "both", linestyle = "--", alpha = 0.5)
ax.legend(frameon = True, fontsize = 9, loc = "best")
plt.savefig("figures/part_g_lr_sensitivity_lasso.pdf", bbox_inches="tight")
plt.close()