import matplotlib.pyplot as plt
import pandas as pd 
import ast
import numpy as np
from matplotlib.ticker import MaxNLocator
from pathlib import Path

# Ensure that the figures directory exists
Path("figures").mkdir(parents=True, exist_ok=True)

# Read general .txt or .csv file and return number values in dictionary
# Generated by Claude (Sept 2026) w/ prompt "can you write a function reading csv and txt files separated by \t, given this writing function (insert writeToFile)"
def readResultsFile(filename):
    df = pd.read_csv(filename, sep="\t") # read file
    data = {}
    for col in df.columns:
        first_val = str(df[col].iloc[0]).strip() # labels
        if first_val.startswith("["): # if array or list
            data[col] = np.array([np.array(ast.literal_eval(v)) for v in df[col]], dtype = object)
        else: # single number values
            data[col] = df[col].to_numpy()
    return data

#
# --------------------------------------------------------------------
# CLOSED FORM
# --------------------------------------------------------------------
#

# -----------------------------------
# OLS closed form no resampling
# -----------------------------------

data = readResultsFile("results/part=a/n=100_noise=0.1_results.txt")

d = data["d"]
params = data["params"] # array of arrays, different length per row
mse = data["MSE"]
r2 = data["R2"]

# MSE
plt.figure(figsize=(3.7, 2.8))
plt.plot(d, mse, label = "MSE", color = "b")
plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel("MSE")
plt.grid()
plt.xlim(np.min(d), np.max(d))
plt.tight_layout()
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.savefig("figures/n=100_noise=0.1_exercise=a_MSE_OLS.pdf", bbox_inches='tight')
#plt.show()

# R2
plt.figure(figsize=(3.7, 2.8))
plt.plot(d, r2, label = "R2 score", color = "r")
plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel(r"R$^2$ score")
plt.grid()
plt.xlim(np.min(d), np.max(d))
plt.tight_layout()
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.savefig("figures/n=100_noise=0.1_exercise=a_R2_OLS.pdf", bbox_inches='tight')
#plt.show()

# Params
# Showing how params grow large with OLS as the model overfits at high variance
norms = [np.linalg.norm(theta) for theta in params]
plt.figure(figsize=(3.7, 2.8))
plt.plot(d, norms, color = "k")
plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel(r"$\|\boldsymbol{\theta}\|_2$")
#plt.title("Parameternorms, OLS, n = 100, noise = 0.1")
plt.xlim(np.min(d), np.max(d))
plt.grid()
plt.tight_layout()
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.savefig("figures/n=100_noise=0.1_exercise=a_param_norm_OLS.pdf", bbox_inches='tight')
#plt.show()
# Heatmap of params
max_len = max(len(theta) for theta in params)
matrix = np.full((len(d), max_len), np.nan)
for i, theta in enumerate(params):
    matrix[i, :len(theta)] = theta
plt.figure(figsize=(3.7, 2.8))
plt.imshow(matrix.T, aspect="auto", cmap="coolwarm")
plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel(r"Coefficient index $(\theta_i)$")
y_labels = np.arange(1, matrix.shape[1] + 1)
plt.yticks(ticks=np.arange(matrix.shape[1])[::2], labels=y_labels[::2])
plt.xticks(ticks=np.arange(len(d))[::2], labels=d[::2])
plt.colorbar(label=r"Coefficient value")
plt.tight_layout()
plt.savefig("figures/n=100_noise=0.1_exercise=a_param_heatmap_OLS.pdf", bbox_inches='tight')
#plt.show()

"""
# Noise and n analysis
noises = [0.05, 0.1, 0.3]
ns = [50, 100, 250, 500]
chosen_d = [1, 3, 6, 8, 10, 11, 12, 13, 14, 15]
# Structure: table[noise][d][n] = MSE
tables = {}
for noise in noises:
    table = np.full((len(chosen_d), len(ns)), np.nan)
    for col, n in enumerate(ns):
        #filename = f"results/n={n}_noise={noise}_exercise=a_results.txt"
        filename = f"results/part=a/n={n}_noise={noise}_results.txt"
        data = readResultsFile(filename)
        for row, d in enumerate(chosen_d):
            mask = data["d"] == d
            table[row, col] = data["MSE"][mask][0]  # one match per d
    tables[noise] = table
# Check
for noise, table in tables.items():
    print(f"\nNoise = {noise}")
    header = "d\\n".ljust(6) + "".join(f"{n:>10}" for n in ns)
    print(header)
    for d, row in zip(chosen_d, table):
        print(f"{d:<6}" + "".join(f"{val:>10.4g}" for val in row))
"""

# -----------------------------------
# Ridge closed form no resampling
# -----------------------------------

data = readResultsFile("results/part=b/n=100_noise=0.1_results.txt")

lamb = data["lambda"]
d = data["d"]
params = data["params"] # array of arrays, different length per row
mse = data["MSE"]
r2 = data["R2"]


# MSE and R2 as func of lambda
chosen_degree = 11
mask = d == chosen_degree
plt.figure(figsize=(3.7, 2.8))
plt.plot(lamb[mask], mse[mask], label = "MSE", color = "b")
plt.xlabel(r"Penalty $(\lambda)$")
plt.ylabel("MSE")
plt.xlim(np.min(lamb), np.max(lamb))
plt.xscale("log")
plt.grid()
plt.tight_layout()
plt.savefig("figures/n=100_noise=0.1_exercise=b_MSE_Ridge.pdf", bbox_inches='tight')
#plt.show()

plt.figure(figsize=(3.7, 2.8))
plt.plot(lamb[mask], r2[mask], label = "R2 score", color = "r")
plt.xlabel(r"Penalty $(\lambda)$")
plt.ylabel(r"R$^2$ score")
plt.xlim(np.min(lamb), np.max(lamb))
plt.xscale("log")
plt.grid()
plt.tight_layout()
plt.savefig("figures/n=100_noise=0.1_exercise=b_R2_Ridge.pdf", bbox_inches='tight')
#plt.show()

# Params
# func of d
available_lambdas = np.unique(lamb)
chosen_lambda = available_lambdas[np.argmin(np.abs(available_lambdas - 0.1))]
mask = lamb == chosen_lambda
norms_lambda = [np.linalg.norm(theta) for theta in params[mask]]
plt.figure(figsize=(3.7, 2.8))
plt.plot(d[mask], norms_lambda, color = "k")
plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel(r"$\|\boldsymbol{\theta}\|_2$")
#plt.title("Parameternorms, Ridge, n = 100, noise = 0.1")
plt.xlim(np.min(d), np.max(d))
plt.grid()
plt.tight_layout()
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.savefig("figures/n=100_noise=0.1_exercise=b_param_of_d_Ridge.pdf", bbox_inches='tight')
#plt.show()
# func of lamda
chosen_degree = 11
mask = d == chosen_degree
norms_degree = [np.linalg.norm(theta) for theta in params[mask]]
plt.figure(figsize=(3.7, 2.8))
plt.plot(lamb[mask], norms_degree, color = "k")
plt.xlabel(r"Penalty $(\lambda)$")
plt.ylabel(r"$\|\boldsymbol{\theta}\|_2$")
#plt.title("Parameternorms, Ridge, n = 100, noise = 0.1")
plt.xlim(np.min(lamb[mask]), np.max(lamb[mask]))
plt.grid()
plt.xscale("log")
plt.tight_layout()
plt.savefig("figures/n=100_noise=0.1_exercise=b_param_of_lam_Ridge.pdf", bbox_inches='tight')
#plt.show()


available_lambdas = np.unique(lamb)
markers = ["o", "s", "^"]
fig, ax = plt.subplots(figsize=(4.5, 2.8))

for lamb_val, marker in zip([available_lambdas[0], available_lambdas[5], available_lambdas[-1]], markers):
    mask = lamb == lamb_val
    ax.plot(d[mask], mse[mask], label=f"λ={lamb_val:.0e}", marker=marker, color="grey", markevery=1)

ax.set_xlabel(r"Polynomial degree $(d)$")
ax.set_ylabel("MSE")
ax.set_xlim(np.min(d), np.max(d))
ax.legend(loc="upper left", bbox_to_anchor=(1.02, 1), frameon=False)
ax.grid()
ax.xaxis.set_major_locator(MaxNLocator(integer=True))

plt.tight_layout()
plt.savefig("figures/n=100_noise=0.1_exercise=b_MSE_given_lam_Ridge.pdf", bbox_inches='tight')
#plt.show()

# --------------------------------------
# Remake Hastie figure for different n
# --------------------------------------

# n = 50
data_c = readResultsFile("results/part=c_Hastie/n=50_noise=0.1_results.txt")
d = data_c["d"]
train_MSE = data_c["Train MSE"]
test_MSE = data_c["Test MSE"]
plt.figure(figsize=(2.7, 2.3))
plt.plot(d, train_MSE, label="Training", color="b")
plt.plot(d, test_MSE, label="Testing", color="palevioletred")
plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel("MSE")
plt.xlim(np.min(d), np.max(d))
plt.title(r"$n = 50$")
plt.grid()
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()
plt.savefig("figures/n=100_noise=0.1_exercise=c_Hastie_50_OLS.pdf", bbox_inches='tight')
#plt.show()
# n = 100
data_c = readResultsFile("results/part=c_Hastie/n=100_noise=0.1_results.txt")
d = data_c["d"]
train_MSE = data_c["Train MSE"]
test_MSE = data_c["Test MSE"]
plt.figure(figsize=(2.5, 2.3))
plt.plot(d, train_MSE, label="Training", color="b")
plt.plot(d, test_MSE, label="Testing", color="palevioletred")
plt.xlabel(r"Polynomial degree $(d)$")
plt.xlim(np.min(d), np.max(d))
plt.title(r"$n = 100$")
plt.grid()
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()
plt.savefig("figures/n=100_noise=0.1_exercise=c_Hastie_OLS.pdf", bbox_inches='tight')
#plt.show()
# n = 500
data_c = readResultsFile("results/part=c_Hastie/n=500_noise=0.1_results.txt")
d = data_c["d"]
train_MSE = data_c["Train MSE"]
test_MSE = data_c["Test MSE"]
plt.figure(figsize=(3.5, 2.3))
plt.plot(d, train_MSE, label="Training", color="b")
plt.plot(d, test_MSE, label="Testing", color="palevioletred")
plt.xlabel(r"Polynomial degree $(d)$")
plt.xlim(np.min(d), np.max(d))
plt.legend(loc="upper left", bbox_to_anchor=(1.02, 1), frameon=False)
plt.grid()
plt.title(r"$n = 500$")
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()
plt.savefig("figures/n=100_noise=0.1_exercise=c_Hastie_500_OLS.pdf", bbox_inches='tight')
#plt.show()

# --------------------------------------
# Bias variance bootstrap
# --------------------------------------

# n = 50
data_c = readResultsFile("results/part=c_tradeoff/n=50_noise=0.1_results.txt")
#deleted the trace of merge conflict here, it was just a comment

d = data_c["degrees"][0]
MSE = data_c["MSE"][0]
bias = data_c["bias"][0]
var = data_c["variance"][0]
plt.figure(figsize=(2.5, 2.3))
plt.plot(d, MSE, label="MSE", color="b")
plt.plot(d, bias, label="Bias", color="grey", marker = "o", markevery=2)
plt.plot(d, var, label="Variance", color="grey", marker = "s", markevery=2)
plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel("Bias Variance decomposition")
plt.xlim(np.min(d), np.max(d))
plt.title(r"$n = 50$")
plt.grid()
plt.yscale("log")
#plt.ylim(0, 0.5)
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()
plt.savefig("figures/n=50_noise=0.1_exercise=c_tradeoff_OLS.pdf", bbox_inches='tight')
#plt.show()

# n = 100
data_c = readResultsFile("results/part=c_tradeoff/n=100_noise=0.1_results.txt")
d = data_c["degrees"][0]
MSE = data_c["MSE"][0]
bias = data_c["bias"][0]
var = data_c["variance"][0]
plt.figure(figsize=(2.3, 2.3))
plt.plot(d, MSE, label="MSE", color="b")
plt.plot(d, bias, label="Bias", color="grey", marker = "o", markevery=2)
plt.plot(d, var, label="Variance", color="grey", marker = "s", markevery=2)
plt.xlabel(r"Polynomial degree $(d)$")
plt.xlim(np.min(d), np.max(d))
plt.title(r"$n = 100$")
plt.grid()
plt.yscale("log")
#plt.ylim(0, 0.5)
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()
plt.savefig("figures/n=100_noise=0.1_exercise=c_tradeoff_OLS.pdf", bbox_inches='tight')
#plt.show()

# n = 500
data_c = readResultsFile("results/part=c_tradeoff/n=500_noise=0.1_results.txt")
d = data_c["degrees"][0]
MSE = data_c["MSE"][0]
bias = data_c["bias"][0]
var = data_c["variance"][0]
plt.figure(figsize=(3.5, 2.3))
plt.plot(d, MSE, label="MSE", color="b")
plt.plot(d, bias, label="Bias", color="grey", marker = "o", markevery=2)
plt.plot(d, var, label="Variance", color="grey", marker = "s", markevery=2)
plt.xlabel(r"Polynomial degree $(d)$")
plt.xlim(np.min(d), np.max(d))
plt.title(r"$n = 500$")
plt.grid()
plt.yscale("log")
plt.legend(loc="upper left", bbox_to_anchor=(1.02, 1), frameon=False)
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()
plt.savefig("figures/n=500_noise=0.1_exercise=c_tradeoff_OLS.pdf", bbox_inches='tight')
#plt.show()




# --------------------------------------
# Part D
# Cross-validation OLS
# --------------------------------------

# n = 50
data_d = readResultsFile("results/part=d_OLS/n=50_noise=0.1_results.txt")
#again, merge conflict trace deleted here. 

k = data_d["k"]
d = data_d["d"]
MSE = data_d["MSE"]

plt.figure(figsize=(2.5, 2.3))

mask5 = k == 5
mask10 = k == 10

plt.plot(d[mask5], MSE[mask5], label="k = 5", color = "midnightblue")
plt.plot(d[mask10], MSE[mask10], label="k = 10", color = "dodgerblue")

plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel("MSE")
plt.xlim(np.min(d), np.max(d))
plt.title(r"$n = 50$")
plt.grid()
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()

plt.savefig(
    "figures/n=50_noise=0.1_exercise=d_MSE_OLS_CV.pdf",
    bbox_inches="tight"
)
# plt.show()


# n = 100
data_d = readResultsFile("results/part=d_OLS/n=100_noise=0.1_results.txt")

k = data_d["k"]
d = data_d["d"]
MSE = data_d["MSE"]

plt.figure(figsize=(2.3, 2.3))

mask5 = k == 5
mask10 = k == 10

plt.plot(d[mask5], MSE[mask5], label="k = 5", color = "midnightblue")
plt.plot(d[mask10], MSE[mask10], label="k = 10", color = "dodgerblue")

plt.xlabel(r"Polynomial degree $(d)$")
plt.xlim(np.min(d), np.max(d))
plt.title(r"$n = 100$")
plt.grid()
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()

plt.savefig(
    "figures/n=100_noise=0.1_exercise=d_MSE_OLS_CV.pdf",
    bbox_inches="tight"
)
# plt.show()

print("CROSS VAL OLS")
k_val = 10
mask = data_d["k"] == k_val
idx_min = np.argmin(data_d["MSE"][mask])
best_d = data_d["d"][mask][idx_min]
best_mse = data_d["MSE"][mask][idx_min]
best_std = data_d["MSE_std"][mask][idx_min]
print(f"k={k_val}: optimal d={best_d}, MSE={best_mse:.5f}, MSE_std={best_std:.5f}")
# k=10: optimal d=10, MSE=0.01330, MSE_std=0.00528

# n = 500
data_d = readResultsFile("results/part=d_OLS/n=500_noise=0.1_results.txt")

k = data_d["k"]
d = data_d["d"]
MSE = data_d["MSE"]

plt.figure(figsize=(3.5, 2.3))

mask5 = k == 5
mask10 = k == 10

plt.plot(d[mask5], MSE[mask5], label="k = 5", color = "midnightblue")
plt.plot(d[mask10], MSE[mask10], label="k = 10", color = "dodgerblue")

plt.xlabel(r"Polynomial degree $(d)$")
plt.xlim(np.min(d), np.max(d))
plt.title(r"$n = 500$")
plt.grid()

plt.legend(
    loc="upper left",
    bbox_to_anchor=(1.02, 1),
    frameon=False
)

plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()

plt.savefig(
    "figures/n=500_noise=0.1_exercise=d_MSE_OLS_CV.pdf",
    bbox_inches="tight"
)
# plt.show()


# -----------------------------------
# Optimal lambda for Ridge
# -----------------------------------

print("CROSS VAL RIDGE")
data = readResultsFile("results/part=d_Ridge/n=100_noise=0.1_results.txt")
# k = 5
k_val = 5
mask = data["k"] == k_val
idx_min = np.argmin(data["MSE"][mask])
best_d = data["d"][mask][idx_min]
best_lambda = data["lambda"][mask][idx_min]
best_mse = data["MSE"][mask][idx_min]
print(f"k={k_val}: optimal d={best_d}, lambda={best_lambda:.3g}, MSE={best_mse:.5f}")
# k = 10
k_val = 10
mask = data["k"] == k_val
idx_min = np.argmin(data["MSE"][mask])
best_d = data["d"][mask][idx_min]
best_lambda = data["lambda"][mask][idx_min]
best_mse = data["MSE"][mask][idx_min]
print(f"k={k_val}: optimal d={best_d}, lambda={best_lambda:.3g}, MSE={best_mse:.5f}")
# Output
# k=5: optimal d=12, lambda=5.59e-08, MSE=0.01294
# k=10: optimal d=12, lambda=8.11e-08, MSE=0.01301


# Global optimal lambda (d, lam) per (n,k)
for n in [50, 100, 500]:
    data = readResultsFile(f"results/part=d_Ridge/n={n}_noise=0.1_results.txt")

    for k_val in [5, 10]:
        mask = data["k"] == k_val

        idx_min = np.argmin(data["MSE"][mask])
        best_d = data["d"][mask][idx_min]
        best_lambda = data["lambda"][mask][idx_min]
        best_mse = data["MSE"][mask][idx_min]
        best_std = data["MSE_std"][mask][idx_min]

        print(f"n={n}, k={k_val}: optimal d={best_d}, lambda={best_lambda:.3g}, MSE={best_mse:.5f}, MSE_std={best_std:.5f}")
# Output
#n=50, k=5: optimal d=12, lambda=5.59e-08, MSE=0.01320, MSE_std=0.00703
#n=50, k=10: optimal d=11, lambda=2.48e-07, MSE=0.01315, MSE_std=0.01100
#n=100, k=5: optimal d=12, lambda=5.59e-08, MSE=0.01294, MSE_std=0.00435
#n=100, k=10: optimal d=12, lambda=8.11e-08, MSE=0.01301, MSE_std=0.00578
#n=500, k=5: optimal d=14, lambda=0, MSE=0.01077, MSE_std=0.00094
#n=500, k=10: optimal d=14, lambda=0, MSE=0.01086, MSE_std=0.00192


# MSE as function of lambda for k = 5 and k = 10, n = 100 and d = 5
data = readResultsFile("results/part=d_Ridge/n=100_noise=0.1_results.txt")
chosen_degree = 5
plt.figure(figsize=(2.6, 2.2))
for k_val, color in zip([5, 10], ["midnightblue", "dodgerblue"]):
    mask = (data["k"] == k_val) & (data["d"] == chosen_degree)
    order = np.argsort(data["lambda"][mask])
    lamb_sorted = data["lambda"][mask][order]
    mse_sorted = data["MSE"][mask][order]
    plt.plot(lamb_sorted, mse_sorted, label=f"k={k_val}", color = color)
plt.xscale("log")
plt.xlabel(r"Penalty $(\lambda)$")
plt.ylabel("MSE")
plt.title("d = 5")
plt.grid()
#plt.xlim(np.min(lamb_sorted), np.max(lamb_sorted))
plt.tight_layout()
plt.savefig("figures/n=100_noise=0.1_exercise=d_MSE_vs_lambda_Ridge_CV_d5.pdf", bbox_inches='tight')
# plt.show()
# MSE as function of lambda for k = 5 and k = 10, n = 100 and d = 10
data = readResultsFile("results/part=d_Ridge/n=100_noise=0.1_results.txt")
chosen_degree = 10
plt.figure(figsize=(2.5, 2.2))
for k_val, color in zip([5, 10], ["midnightblue", "dodgerblue"]):
    mask = (data["k"] == k_val) & (data["d"] == chosen_degree)
    order = np.argsort(data["lambda"][mask])
    lamb_sorted = data["lambda"][mask][order]
    mse_sorted = data["MSE"][mask][order]
    plt.plot(lamb_sorted, mse_sorted, label=f"k={k_val}", color = color)
plt.xscale("log")
plt.xlabel(r"Penalty $(\lambda)$")
plt.title("d = 10")
plt.grid()
#plt.xlim(np.min(lamb_sorted), np.max(lamb_sorted))
plt.tight_layout()
plt.savefig("figures/n=100_noise=0.1_exercise=d_MSE_vs_lambda_Ridge_CV_d10.pdf", bbox_inches='tight')
# plt.show()
# MSE as function of lambda for k = 5 and k = 10, n = 100 and d = 14
data = readResultsFile("results/part=d_Ridge/n=100_noise=0.1_results.txt")
chosen_degree = 14
plt.figure(figsize=(3.1, 2.2))
for k_val, color in zip([5, 10], ["midnightblue", "dodgerblue"]):
    mask = (data["k"] == k_val) & (data["d"] == chosen_degree)
    order = np.argsort(data["lambda"][mask])
    lamb_sorted = data["lambda"][mask][order]
    mse_sorted = data["MSE"][mask][order]
    plt.plot(lamb_sorted, mse_sorted, label=f"k={k_val}", color = color)
plt.xscale("log")
plt.xlabel(r"Penalty $(\lambda)$")
plt.legend(
    loc="upper left",
    bbox_to_anchor=(1.02, 1),
    frameon=False
)
plt.title("d = 14")
plt.grid()
plt.xlim(np.min(lamb_sorted), np.max(lamb_sorted))
plt.tight_layout()
plt.savefig("figures/n=100_noise=0.1_exercise=d_MSE_vs_lambda_Ridge_CV_d14.pdf", bbox_inches='tight')
# plt.show()


# MSE as function of d, for all different n, with set optimal lambda for each
# MSE as function of polynomial degree for n = 50
data = readResultsFile("results/part=d_Ridge/n=50_noise=0.1_results.txt")
plt.figure(figsize=(2.5, 2.2))
for k_val, color, chosen_lambda in zip(
    [5, 10],
    ["midnightblue", "dodgerblue"],
    [5.59e-08, 3.85e-08]
):
    mask = (
        (data["k"] == k_val)
        & np.isclose(data["lambda"], chosen_lambda)
    )

    order = np.argsort(data["d"][mask])
    d_sorted = data["d"][mask][order]
    mse_sorted = data["MSE"][mask][order]
    plt.plot(
        d_sorted,
        mse_sorted,
        label=f"k={k_val}",
        color=color
    )
plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel("MSE")
plt.grid()
plt.title("n = 50")
plt.xlim(np.min(d_sorted), np.max(d_sorted))
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()
plt.savefig(
    "figures/n=50_noise=0.1_exercise=d_MSE_vs_degree_Ridge_CV.pdf",
    bbox_inches="tight"
)
# plt.show()
# MSE as function of polynomial degree for n = 100
data = readResultsFile("results/part=d_Ridge/n=100_noise=0.1_results.txt")
plt.figure(figsize=(2.4, 2.2))
for k_val, color, chosen_lambda in zip(
    [5, 10],
    ["midnightblue", "dodgerblue"],
    [1.18e-07, 9.77e-08]
):
    mask = (
        (data["k"] == k_val)
        & np.isclose(data["lambda"], chosen_lambda)
    )
    order = np.argsort(data["d"][mask])
    d_sorted = data["d"][mask][order]
    mse_sorted = data["MSE"][mask][order]
    plt.plot(
        d_sorted,
        mse_sorted,
        label=f"k={k_val}",
        color=color
    )
plt.xlabel(r"Polynomial degree $(d)$")
plt.grid()
plt.title("n = 100")
plt.xlim(np.min(d_sorted), np.max(d_sorted))
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()
plt.savefig(
    "figures/n=100_noise=0.1_exercise=d_MSE_vs_degree_Ridge_CV.pdf",
    bbox_inches="tight"
)
# plt.show()
# MSE as function of polynomial degree for n = 500
data = readResultsFile("results/part=d_Ridge/n=500_noise=0.1_results.txt")
plt.figure(figsize=(3.1, 2.2))
for k_val, color in zip(
    [5, 10],
    ["midnightblue", "dodgerblue"]
):
    chosen_lambda = 0.0
    mask = (
        (data["k"] == k_val)
        & np.isclose(data["lambda"], chosen_lambda)
    )
    order = np.argsort(data["d"][mask])
    d_sorted = data["d"][mask][order]
    mse_sorted = data["MSE"][mask][order]
    plt.plot(
        d_sorted,
        mse_sorted,
        label=f"k={k_val}",
        color=color
    )
plt.xlabel(r"Polynomial degree $(d)$")
plt.legend(
    loc="upper left",
    bbox_to_anchor=(1.02, 1),
    frameon=False
)
plt.grid()
plt.xlim(np.min(d_sorted), np.max(d_sorted))
plt.title("n = 500")
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()
plt.savefig(
    "figures/n=500_noise=0.1_exercise=d_MSE_vs_degree_Ridge_CV.pdf",
    bbox_inches="tight"
)
# plt.show()

# # -----------------------------------
# # Part D
# # Cross-validation Ridge
# # -----------------------------------

# num_points = [50, 100, 500]
# noise = 0.1

# for n in num_points:

#     data = readResultsFile(
#         f"results/part=d_Ridge/n={n}_noise={noise}_results.txt"
#     )

#     k = data["k"]
#     d = data["d"]
#     lamb = data["lambda"]
#     mse = data["MSE"]

#     plt.figure(figsize=(3.7, 2.8))

#     for lam in np.unique(lamb):

#         mask5 = (k == 5) & (lamb == lam)
#         mask10 = (k == 10) & (lamb == lam)

#         plt.plot(
#             d[mask5], mse[mask5],
#             label=fr"$\lambda={lam:.1e}$, k=5",
#         )

#         plt.plot(
#             d[mask10], mse[mask10],
#             linestyle="--",
#             label=fr"$\lambda={lam:.1e}$, k=10"
#         )

#     plt.xlabel(r"Polynomial degree $(d)$")
#     plt.ylabel("MSE")
#     plt.title(f"n = {n}")
#     plt.grid()
#     plt.xlim(np.min(d), np.max(d))

#     # Place legend to the right of the plot
#     plt.legend(
#         fontsize=6,
#         loc="center left",
#         bbox_to_anchor=(1.02, 0.5)
#     )

#     plt.tight_layout()
#     plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))

#     plt.savefig(
#         f"figures/n={n}_noise={noise}_exercise=d_MSE_Ridge_CV.pdf",
#         bbox_inches="tight"
#     )

#     plt.show()


# =====================================================================
# HERE WE CAN CHANGE THE PLOT COLOURS
# =====================================================================

# Unified method styles with solid lines for all gradient descent variants
method_styles = {
    "plain": {"color": "gold", "linestyle": "-", "label": "Plain GD"},
    "momentum": {"color": "black", "linestyle": "-", "label": "Momentum"},
    "adagrad": {"color": "indianred", "linestyle": "-", "label": "AdaGrad"},
    "rmsprop": {"color": "royalblue", "linestyle": "-", "label": "RMSprop"},
    "adam": {"color": "yellowgreen", "linestyle": "-", "label": "Adam"}
}

methods = list(method_styles.keys())
models = ["OLS", "Ridge"]
chosen_lambda = 0.01  # for Ridge






# =====================================================================
# Exercise i)
# Optimal lambda for Lasso found in part_i.py
# =====================================================================


# # ------------------------------------------------------------------------
# # Part i)
# # Compare MSE for OLS, Ridge and Lasso for different polynomial degrees
# # ------------------------------------------------------------------------

# # Read results
# data_ols = readResultsFile("results/part=d_OLS/n=100_noise=0.1_results.txt")
# data_ridge = readResultsFile("results/part=d_Ridge/n=100_noise=0.1_results.txt")
# data_lasso = readResultsFile(
#     "results/part=i_Lasso/n=100_noise=0.1_type=adam_vs_degree_results.txt"
# )

# # -------------------------------------------------------------
# # OLS, k = 10
# # -------------------------------------------------------------
# mask_ols = data_ols["k"] == 10

# d_ols = data_ols["d"][mask_ols]
# mse_ols = data_ols["MSE"][mask_ols]


# # -------------------------------------------------------------
# # Ridge, k = 10 and optimal lambda
# # -------------------------------------------------------------
# ridge_lamb = 8.11e-8

# mask_ridge = (
#     (data_ridge["k"] == 10)
#     & np.isclose(data_ridge["lambda"], ridge_lamb, rtol=0.05)
# )

# d_ridge = data_ridge["d"][mask_ridge]
# mse_ridge = data_ridge["MSE"][mask_ridge]


# # -------------------------------------------------------------
# # Lasso with Adam
# # -------------------------------------------------------------
# d_lasso = data_lasso["degree"]
# mse_lasso = data_lasso["MSE"]


# # -------------------------------------------------------------
# # Plot
# # -------------------------------------------------------------
# plt.figure(figsize=(3.1, 2.2))

# plt.plot(d_ols, mse_ols, label="OLS", color = "midnightblue")
# plt.plot(d_ridge, mse_ridge, label="Ridge", color = "maroon")
# plt.plot(d_lasso, mse_lasso, label="Lasso", color = "green")

# plt.xlabel(r"Polynomial degree $(d)$")
# plt.ylabel("MSE")
# plt.xlim(1, 15)
# plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
# plt.grid()
# plt.legend()

# plt.tight_layout()

# plt.savefig(
#     "figures/n=100_noise=0.1_exercise=i_MSE_OLS_Ridge_Lasso.pdf"
# )

# plt.close()

# -----------------------------------------------------------------------------------
# Part i)
# Plot data with optimal OLS, Ridge and Lasso models
# -----------------------------------------------------------------------------------

from sklearn.model_selection import train_test_split
from utils import *

# Load optimal parameters from cross-validation with k = 10


# Adam parameters for Lasso
gamma = 0.55
target_tol = 1e-8
max_iters_cap = 10000



# # -------------------------------------------------------------
# # OLS
# # -------------------------------------------------------------

# X = MakeDesignMatrix(x, d_ols)
# X_plot = MakeDesignMatrix(x_plot, d_ols)

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=69
# )

# X_train_scaled, X_plot_scaled, y_train_centered = scaleData(
#     X_train, X_plot, y_train
# )

# params_ols = closedForm(
#     X_train_scaled,
#     y_train_centered
# )

# y_plot_ols = X_plot_scaled @ params_ols + y_train.mean()


# # -------------------------------------------------------------
# # Ridge
# # -------------------------------------------------------------

# X = MakeDesignMatrix(x, d_ridge)
# X_plot = MakeDesignMatrix(x_plot, d_ridge)

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=69
# )

# X_train_scaled, X_plot_scaled, y_train_centered = scaleData(
#     X_train, X_plot, y_train
# )

# params_ridge = closedForm(
#     X_train_scaled,
#     y_train_centered,
#     lamb=lambda_ridge
# )

# y_plot_ridge = X_plot_scaled @ params_ridge + y_train.mean()


# # -------------------------------------------------------------
# # Lasso with Adam
# # -------------------------------------------------------------

# X = MakeDesignMatrix(x, d_lasso)
# X_plot = MakeDesignMatrix(x_plot, d_lasso)

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=69
# )

# X_train_scaled, X_plot_scaled, y_train_centered = scaleData(
#     X_train, X_plot, y_train
# )

# theta_init = np.zeros(X_train_scaled.shape[1])

# history_lasso = optimise(
#     grad=lambda th: GradLassoAnalytic(
#         th,
#         X_train_scaled,
#         y_train_centered,
#         lambda_lasso
#     ),
#     theta0=theta_init,
#     method="adam",
#     gamma=gamma,
#     num_iters=max_iters_cap,
#     tol=target_tol
# )

# params_lasso = history_lasso[-1]

# y_plot_lasso = X_plot_scaled @ params_lasso + y_train.mean()


# # -------------------------------------------------------------
# # Plot
# # -------------------------------------------------------------

# plt.figure(figsize=(3.7, 2.8))

# plt.scatter(x, y, label="Data", s=8, color = "grey")

# plt.plot(x_plot, y_plot_ols, label="OLS", color = "midnightblue")
# plt.plot(x_plot, y_plot_ridge, label="maroon")
# plt.plot(x_plot, y_plot_lasso, label="green")

# plt.xlabel(r"$x$")
# plt.ylabel(r"$y$")
# plt.grid()
# plt.legend()

# plt.tight_layout()

# plt.savefig(
#     "figures/n=100_noise=0.1_exercise=i_OLS_Ridge_Lasso_data.pdf",
#     bbox_inches="tight"
# )

# plt.close()


# CV-MSE optimal
data = readResultsFile("results/part=i_Lasso/n=100_noise=0.1_results.txt")
mask = data["k"] == 10
idx = np.argmin(data["MSE"][mask])
print(f"Lasso k=10: d = {data['d'][mask][idx]}, lambda = {data['lambda'][mask][idx]:.3e}, "
      f"CV-MSE = {data['MSE'][mask][idx]:.5f}, MSE_std = {data['MSE_std'][mask][idx]:.5f}")



# Predictions
fp = readResultsFile(
    "results/part=final/n=100_noise=0.1_type=final_fit_predictions_results.txt"
)
dp = readResultsFile(
    "results/part=final/n=100_noise=0.1_type=final_fit_data_results.txt"
)
train = dp["set"] == "train"
test = dp["set"] == "test"

plt.figure(figsize=(4.5, 2.6))
plt.plot(fp["x"], fp["OLS"], label="OLS", color="b")
plt.plot(fp["x"], fp["Ridge"], label="Ridge", color="r")
plt.plot(fp["x"], fp["Lasso"], label="Lasso", color="yellowgreen")
plt.scatter(dp["x"][train], dp["y"][train], s=8, color="grey", label="Train")
plt.scatter(dp["x"][test], dp["y"][test], s=12, facecolors="none",edgecolors="black", label="Test")
plt.xlabel(r"$x$")
plt.ylabel(r"Prediction ($\hat{y}$)")
plt.grid()
plt.xticks(np.arange(-1, 1.01, 0.5))
plt.yticks(np.arange(-0.21, 1.21, 0.2))  
plt.xlim(np.min(fp["x"]), np.max(fp["x"]))
plt.legend(
    loc="upper left",
    bbox_to_anchor=(1.02, 1),
    frameon=False
)
plt.tight_layout()
plt.savefig("figures/n=100_noise=0.1_exercise=i_final_fit.pdf", bbox_inches="tight")
plt.close() 


# final test MSE
ft = readResultsFile("results/part=i/n=100_noise=0.1_type=final_test_results.txt")
for i, name in enumerate(["OLS", "Ridge", "Lasso"]):
    print(f"{name}: test MSE = {ft['MSE'][i]:.5f}, SE = {ft['SE'][i]:.5f}")
#OLS: test MSE = 0.01409, SE = 0.00470
#Ridge: test MSE = 0.01366, SE = 0.00458
#Lasso: test MSE = 0.01698, SE = 0.00604





# ====================================================================================================
# PART E: here we have two plotting scripts - one to plot MSE and R2 score for GD vs CF (both OLS and Ridge), 
# and another one to test how many iterations it takes to reach convergence (based on the criterion we defined)
# ====================================================================================================
data_e = readResultsFile("results/part=e/n=100_noise=0.1_results.txt")

# --- OLS MSE & R2 Comparisons ---

# Extract the data we need
ols_mask = data_e["model"] == "OLS"
d_ols = data_e["d"][ols_mask]
mse_gd_ols = data_e["MSE_GD"][ols_mask]
mse_cf_ols = data_e["MSE_CF"][ols_mask]
r2_gd_ols = data_e["R2_GD"][ols_mask]
r2_cf_ols = data_e["R2_CF"][ols_mask]


plt.figure(figsize=(3.0, 2.8))
plt.plot(d_ols, mse_gd_ols, label="Gradient descent", color="royalblue", linestyle="-", linewidth=2.0, zorder=1)
plt.plot(d_ols, mse_cf_ols, label="Closed form", color="red", linestyle="--", linewidth=1.2, zorder=2)
plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel("MSE")
plt.title("OLS")
plt.grid(True)
plt.xlim(np.min(d_ols), np.max(d_ols))
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()
plt.savefig("figures/part=e_OLS_MSE_comparison.pdf", bbox_inches="tight")
plt.close()


plt.figure(figsize=(3.0, 2.8))
plt.plot(d_ols, r2_gd_ols, label="Gradient descent", color="royalblue", linestyle="-", linewidth=2.0, zorder=1)
plt.plot(d_ols, r2_cf_ols, label="Closed form", color="red", linestyle="--", linewidth=1.2, zorder=2)
plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel(r"$R^2$ Score")
plt.grid(True)
plt.title("OLS")
plt.legend(frameon=False)
plt.xlim(np.min(d_ols), np.max(d_ols))
plt.tight_layout()
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.savefig("figures/part=e_OLS_R2_comparison.pdf", bbox_inches="tight")
plt.close()

# --- Ridge MSE & R2 Comparisons ---

# Extract the data
ridge_mask = (data_e["model"] == "Ridge") & np.isclose(
    data_e["lambda"], chosen_lambda, rtol=1e-3, atol=1e-4
)
d_ridge = data_e["d"][ridge_mask]
mse_gd_ridge = data_e["MSE_GD"][ridge_mask]
mse_cf_ridge = data_e["MSE_CF"][ridge_mask]
r2_gd_ridge = data_e["R2_GD"][ridge_mask]
r2_cf_ridge = data_e["R2_CF"][ridge_mask]


plt.figure(figsize=(3.0, 2.8))
plt.plot(d_ridge, mse_gd_ridge, label="Gradient descent", color="royalblue", linestyle="-", linewidth=2.0, zorder=1)
plt.plot(d_ridge, mse_cf_ridge, label="Closed form", color="red", linestyle="--", linewidth=1.2, zorder=2)
plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel("MSE")
plt.grid(True)
plt.title("Ridge")
plt.xlim(np.min(d_ridge), np.max(d_ridge))
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()
plt.savefig("figures/part=e_Ridge_MSE_comparison.pdf", bbox_inches="tight")
plt.close()


plt.figure(figsize=(3.0, 2.8))
plt.plot(d_ridge, r2_gd_ridge, label="Gradient descent", color="royalblue", linestyle="-", linewidth=2.0, zorder=1)
plt.plot(d_ridge, r2_cf_ridge, label="Closed form", color="red", linestyle="--", linewidth=1.2, zorder=2)
plt.xlabel(r"Polynomial degree $(d)$")
plt.ylabel(r"$R^2$ Score")
plt.grid(True)
plt.xlim(np.min(d_ridge), np.max(d_ridge))
plt.title("Ridge")
plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
plt.tight_layout()
plt.savefig("figures/part=e_Ridge_R2_comparison.pdf", bbox_inches="tight")
plt.close()

# --- Iterations to reach convergence ---
for model_name in models:
    plt.figure(figsize=(3.0, 2.5))
    plt.title(model_name)
    # Extract the data
    if model_name == "OLS":
        m_mask = data_e["model"] == "OLS"
        degrees = data_e["d"][m_mask]
        iters = data_e["iters_needed"][m_mask]
        plt.ylabel(r"Iterations to reach $\|\mathbf{g}\| < 10^{-8}$")
    else:
        m_mask = data_e["model"] == "Ridge"
        l_mask = m_mask & np.isclose(data_e["lambda"], chosen_lambda, rtol=1e-3, atol=1e-4)
        degrees = data_e["d"][l_mask]
        iters = data_e["iters_needed"][l_mask]
        
    plt.plot(
        degrees,
        iters,
        color="midnightblue",
        linestyle="-",
        linewidth=1.5
    )

    # Plot 10,000 iteration cap line
    plt.axhline(10000, color="red", linestyle="--", alpha=0.5, linewidth=1.0, label="Iteration cap")

    plt.xlabel(r"Polynomial degree $(d)$")
    plt.yscale("log")
    plt.ylim(1, 20000)
    plt.legend(fontsize=10, frameon=True)
    plt.grid(True, which="both", linestyle="--", alpha=0.5)
    plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
    plt.xlim(1, 15)
    plt.tight_layout()
    
    filename = f"figures/part=e_{model_name.lower()}_iters_vs_degree.pdf"
    plt.savefig(filename, bbox_inches="tight")
    plt.close()


# ===========================================================================
# PART F: in this part we have two plotting scripts - one to plot
# the sensitivity to learning rate (for a fixed degree d = 5) and one to plot
# the iterations required to reach a convergence threshold (for all degrees) 
# with a fixed (initial) learning rate gamma = 0.01
# ===========================================================================
data_f = readResultsFile("results/part=f/n=100_type=iters_vs_degree_results.txt")

# --- Iterations to reach convergence ---

figsizes = {"OLS": (3.0, 2.5), "Ridge": (4.2, 2.5)}

for model_name in models:
    plt.figure(figsize=figsizes[model_name])

    model_mask = data_f["model"] == model_name

    for method, style in method_styles.items():
        method_mask = model_mask & (data_f["method"] == method)
        if not np.any(method_mask):
            continue

        degrees = data_f["degree"][method_mask]
        iters = data_f["iters_needed"][method_mask]

        plt.plot(
            degrees,
            iters,
            label=style["label"],
            color=style["color"],
            linestyle=style["linestyle"],
            linewidth=1.5
        )

    # Plot 10,000 iteration cap line
    plt.axhline(10000, color="red", linestyle="--", alpha=0.5, linewidth=1.0, label="Iteration cap")

    plt.title(model_name)
    plt.xlabel(r"Polynomial degree $(d)$")

    if model_name == "OLS":
        plt.ylabel(r"Iterations to reach $\|\mathbf{g}\| < 10^{-8}$")
    else:
        plt.legend(loc="upper left", bbox_to_anchor=(1.02, 1), frameon=False)

    plt.yscale("log")
    plt.ylim(1, 20000)
    plt.xlim(1, 15)
    plt.grid(True, which="both", linestyle="--", alpha=0.5)
    plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
    plt.tight_layout()

    filename = f"figures/part=f_{model_name}_iters_vs_degree.pdf"
    plt.savefig(filename, bbox_inches="tight")
    plt.close()


# --- Learning rate sensitivity (final theta error as a function of (initial) learning rate) ---


def lr_sens_plot(lr, err, meth, figsize, filename, title, ylabel=None, legend=False, extra=None):
    fig, ax = plt.subplots(figsize=figsize)
    for method, style in method_styles.items():
        mask = meth == method
        if np.any(mask):
            ax.plot(lr[mask], err[mask], color=style["color"], linestyle=style["linestyle"],
                    linewidth=1.8, label=style["label"])
    if extra is not None:  # soft thresholding (only Lasso)
        mask = meth == extra["method"]
        ax.plot(lr[mask], err[mask], color=extra["color"], linestyle=extra["linestyle"],
                linewidth=1.8, label=extra["label"])
    ax.axhline(1e-8, color="black", linestyle="--", alpha=0.7, label=r"Target ($10^{-8}$)")
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_ylim(1e-12, 1e3)
    ax.set_title(title)
    ax.set_xlim(np.min(lr), np.max(lr))
    ax.set_xlabel(r"Initial learning rate ($\gamma$)")
    if ylabel is not None:
        ax.set_ylabel(ylabel)
    ax.grid(True, which="both", linestyle="--", alpha=0.5)
    if legend:
        ax.legend(loc="upper left", bbox_to_anchor=(1.02, 1), frameon=False)
    plt.tight_layout()
    plt.savefig(filename, bbox_inches="tight")
    plt.close()


# OLS and Ridge (part f)
data_sens = readResultsFile(Path("results") / "part=f" / "n=100_type=lr_sensitivity_results.txt")
lam = data_sens["lambda"]

ols = lam == 0.0
lr_sens_plot(data_sens["learning_rate"][ols], data_sens["final_param_error"][ols],
             data_sens["method"][ols], figsize=(3.0, 2.3), title="OLS",
             filename="figures/part_f_lr_sensitivity_ols.pdf",
             ylabel=r"$\max |\boldsymbol{\theta}_{\mathrm{final}} - \boldsymbol{\theta}_{\mathrm{CF}}|$")

ridge = lam == 0.01
lr_sens_plot(data_sens["learning_rate"][ridge], data_sens["final_param_error"][ridge],
             data_sens["method"][ridge], figsize=(3.0, 2.3), title="Ridge",
             filename="figures/part_f_lr_sensitivity_ridge.pdf")

# Lasso (part g)
data_lr = readResultsFile(Path("results") / "part=g" / "n=100_noise=0.1_d=5_lambda=0.01_type=lr_sensitivity_results.txt")
lr_sens_plot(data_lr["learning_rate"], data_lr["final_param_error"], data_lr["method"],
             figsize=(4.7, 2.3), title="Lasso", filename="figures/part_g_lr_sensitivity_lasso.pdf",
             ylabel=r"$\max |\boldsymbol{\theta}_{\mathrm{final}} - \boldsymbol{\theta}_{\mathrm{sklearn}}|$",
             legend=True,
             extra={"method": "soft_threshold", "color": "darkorange",
                    "linestyle": "-.", "label": "Soft thresholding"})



# ======================================================================================================
# PART H: in this part we have two plotting scripts - one to plot
# final theta error as a function of total gradient evaluations (Adam with SDG, different batch sizes M),
# another one it to compare fixed lr vs ler decaying schedule (BUT I NEED TO FIX THIS ONE I THINK)
# P.s. this is done for polynomial degree d=5
# ======================================================================================================


degree = 5
results_dir = Path("results") / "part=h"
models = ["ols", "ridge", "lasso"]
titles = {"ols": "OLS", "ridge": "Ridge", "lasso": "Lasso"}
figsizes_h = {"ols": (2.8, 2.5), "ridge": (2.7, 2.5), "lasso": (5.2, 2.5)}

for model_name in models:
    # --- File paths updated to load Adam results ---
    batch_file = results_dir / f"type=batch_sensitivity_adam_{model_name}_degree={degree}_results.txt"
    if not batch_file.exists():
        continue
        
    batch_data = readResultsFile(batch_file)
    unique_batches = np.unique(batch_data["batch_size"])
    palette = [style["color"] for style in method_styles.values()]

    # ==========================================
    # Batch size error vs. total gradient evaluations
    # ==========================================
    fig, ax = plt.subplots(figsize=figsizes_h[model_name])
    for i, M in enumerate(unique_batches):
        mask = batch_data["batch_size"] == M
        ax.plot(batch_data["total_evals"][mask], batch_data["final_param_error"][mask],
            label=f"M = {M}", color=palette[i])

    ax.axhline(1e-8, color="black", linestyle="--", alpha=0.6, label=r"Target ($10^{-8}$)")
    ax.set_yscale("log")
    ax.set_xscale("log")
    ax.set_title(titles[model_name])
    ax.set_xlabel("Total Gradient Evaluations")
    if model_name == "ols":
        ax.set_ylabel(r"$\max |\boldsymbol{\theta}_{\mathrm{final}} - \boldsymbol{\theta}_{\mathrm{CF}}|$")
    if model_name == "lasso":
        ax.set_ylabel(r"$\max |\boldsymbol{\theta}_{\mathrm{final}} - \boldsymbol{\theta}_{\mathrm{sklearn}}|$")
        ax.legend(loc="upper left", bbox_to_anchor=(1.02, 1), frameon=False)
    ax.grid(True, which="both", linestyle="--", alpha=0.4)

    ax.set_ylim(bottom=1e-9, top=10.0)
    ax.set_xlim(right=100000)

    plt.tight_layout()
    plt.savefig(f"figures/part_h_batch_sensitivity_adam_evals_{model_name}.pdf", bbox_inches="tight")
    plt.close()


    # ==========================================
    # Constant vs. scheduled learning rate
    # ==========================================
    sched_file = results_dir / f"type=lr_schedule_adam_{model_name}_degree={degree}_results.txt"
    if not sched_file.exists():
        continue

    sched_data = readResultsFile(sched_file)
    unique_schedules = np.unique(sched_data["schedule"])
    colors = {"constant": "#d62728", "scheduled_1": "#1f77b4"}
    labels = {"constant": r"Constant ($\gamma = 0.01$)", "scheduled_1": r"Scheduled ($t_0=5, t_1=50$)"}

    fig, ax = plt.subplots(figsize=figsizes_h[model_name])
    for sched_name in unique_schedules:
        mask = sched_data["schedule"] == sched_name
        ax.plot(
            sched_data["total_evals"][mask],
            sched_data["final_param_error"][mask],
            label=labels.get(sched_name, sched_name),
            color=colors.get(sched_name, None)
        )

    ax.axhline(1e-8, color="black", linestyle="--", alpha=0.6, label=r"Target ($10^{-8}$)")
    ax.set_yscale("log")
    ax.set_xscale("log")
    ax.set_title(titles[model_name])
    ax.set_xlabel("Total Gradient Evaluations")
    if model_name == "ols":
        ax.set_ylabel(r"$\max |\boldsymbol{\theta}_{\mathrm{final}} - \boldsymbol{\theta}_{\mathrm{CF}}|$")
    if model_name == "lasso":
        ax.set_ylabel(r"$\max |\boldsymbol{\theta}_{\mathrm{final}} - \boldsymbol{\theta}_{\mathrm{sklearn}}|$")
        ax.legend(loc="upper left", bbox_to_anchor=(1.02, 1), frameon=False)
    ax.grid(True, which="both", linestyle="--", alpha=0.4)

    ax.set_ylim(bottom=1e-9, top=10.0)
    ax.set_xlim(right=100000)

    plt.tight_layout()
    plt.savefig(f"figures/part_h_lr_schedule_adam_comparison_{model_name}.pdf", bbox_inches="tight")
    plt.close() 